name: Ubuntu Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Ubuntu Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build libgles2-mesa-dev
    
    - name: Build
      run: |
        mkdir build 
        cd build
        cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release
        ninja Galena
